---
- name: Create AWS infrastructure with Terraform
  hosts: localhost
  connection: local
  vars:
    state: present
    s3_bucket: jentf-state-store
    key: terraform.tfstate
    region: us-east-1
    app_env: dev

  gather_facts: false
  tasks:
  - name: Run terraform scripts
    terraform:
      project_path: "./"
      state: present
      backend_config:
        region: "{{ region }}"
        bucket: "{{ s3_bucket }}"
        key: "{{ key }}"
      variables_file: "{{ app_env }}.tfvars"
      workspace: "{{ app_env }}"

     
