---
- name: Jenkins-Ansible integration
  hosts: localhost
  connection: local
  tasks:
  - name: Installing boto3
    pip:
      name: boto
      state: present

  - name: Creating S3 bucket
    s3_bucket:
      name: jentf-state-store
      state: present
