---
- name: Create S3 bucket and DynamoDB
  hosts: localhost
  connection: local
  tasks:
  - name: Installing boto
    pip:
      name: boto
      state: present
  - name: Creating DynamoDB
    dynamodb_table: 
      name: jenkins-tf
      region: us-east-1
      hash_key_name: LockID
      hash_key_type: STRING
      state: present


    
  - name: Creating S3 bucket
    s3_bucket:
      name: jentf-state-store
      state: present
